'Section 3: 3D Fisher $(f_{\\rm NL}, n_s, A_s)$ with Planck priors; $f_{\\rm NL}^{\\rm fid}$ grid.'

from __future__ import annotations

if __package__ in (None, ""):
    import sys
    from pathlib import Path
    _ROOT = Path(__file__).resolve().parent.parent
    if str(_ROOT) not in sys.path:
        sys.path.insert(0, str(_ROOT))


import json

from beam import W_MU_INV_PIXIE, W_MU_INV_SPECTER
from fisher_matrix import SIGMA_AS_PLANCK2018, default_ell_grid, fisher_muT_general
from output_paths import ensure_section_layout, paper_results_dir

FWHM_PIXIE = 1.6
FWHM_SPECTER = 1.0
NS_FID = 0.965
K_D_I = 1.1e4
K_D_F = 46.0
K_P = 0.002
FNL_FIDUCIALS = (1.0, 10.0, 1000.0, 15000.0, 25000.0)
SIGMA_NS_DEFAULT = 0.004
PRIOR_SWEEP = (0.002, 0.004, 0.008, 0.016)


def _run_grid(*, experiment):
    if experiment == "pixie":
        fwhm, w_inv = FWHM_PIXIE, W_MU_INV_PIXIE
    else:
        fwhm, w_inv = FWHM_SPECTER, W_MU_INV_SPECTER
    ell = default_ell_grid(fwhm)
    rows = []
    for fnl in FNL_FIDUCIALS:
        r = fisher_muT_general(
            ell,
            fwhm,
            fnl,
            NS_FID,
            K_D_I,
            K_D_F,
            K_P,
            w_mu_inv=w_inv,
            dns_step=5e-5,
            sigma_ns_prior=SIGMA_NS_DEFAULT,
            sigma_As_prior=SIGMA_AS_PLANCK2018,
            use_b_analytic=False,
        )
        rows.append(
            {
                "experiment": experiment,
                "fnl_fid": fnl,
                "sigma_fnl_marg": r.sigma_fnl_marg,
                "sigma_ns_marg": r.sigma_ns_marg,
                "sigma_As_marg": r.sigma_As_marg or float("nan"),
                "corr_fnl_ns": r.corr_fnl_ns,
            }
        )
    return rows


def _prior_sweep(*, experiment):
    fwhm, w_inv = (FWHM_PIXIE, W_MU_INV_PIXIE) if experiment == "pixie" else (FWHM_SPECTER, W_MU_INV_SPECTER)
    ell = default_ell_grid(fwhm)
    lines = ["sigma_ns_prior,sigma_fnl_marg,fnl_fid"]
    fnl_ref = 25000.0
    for sp in PRIOR_SWEEP:
        r = fisher_muT_general(
            ell,
            fwhm,
            fnl_ref,
            NS_FID,
            K_D_I,
            K_D_F,
            K_P,
            w_mu_inv=w_inv,
            dns_step=5e-5,
            sigma_ns_prior=sp,
            sigma_As_prior=SIGMA_AS_PLANCK2018,
            use_b_analytic=False,
        )
        lines.append(f"{sp},{r.sigma_fnl_marg:.8e},{fnl_ref}")
    return lines


def _write_latex_table(rows_by_exp):
    """Emit a short pointer under cmbs4/results; the merged 2D+3D table is maintained in main.tex."""
    out = paper_results_dir() / "section3_fnl_ns_as_table.tex"
    pix = {r["fnl_fid"]: r for r in rows_by_exp["pixie"]}
    sp = {r["fnl_fid"]: r for r in rows_by_exp["specter"]}
    lines = [
        "% Auto-generated by run_section3.py — copy 3D \\sigma(f_{NL}) into Table "
        r"tab:fnl_constraints in main.tex (PIXIE / SPECTER columns).",
        "%",
    ]
    for fnl in FNL_FIDUCIALS:
        lines.append(
            f"% f_NL^fid={fnl:g}: PIXIE sigma(f_NL)={pix[fnl]['sigma_fnl_marg']:.6f}  "
            f"SPECTER sigma(f_NL)={sp[fnl]['sigma_fnl_marg']:.6f}"
        )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    dirs = ensure_section_layout("section3_extension", "analytic_cltt_analytic_b")
    (dirs["logs"] / "config.json").write_text(
        json.dumps({"fnl_fiducials": FNL_FIDUCIALS, "sigma_ns": SIGMA_NS_DEFAULT}, indent=2),
        encoding="utf-8",
    )

    rows_pix = _run_grid(experiment="pixie")
    rows_sp = _run_grid(experiment="specter")
    lines = ["# Section 3 — 3D Fisher (f_NL, n_s, A_s), numerical b, analytic Cl_TT"]
    for r in rows_pix + rows_sp:
        lines.append(
            f"{r['experiment']}\t{r['fnl_fid']}\t{r['sigma_fnl_marg']:.8e}\t"
            f"{r['sigma_ns_marg']:.8e}\t{r['sigma_As_marg']:.8e}\t{r['corr_fnl_ns']:.6f}"
        )
    (dirs["tables"] / "forecast_3d_grid.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")

    sweep_lines = _prior_sweep(experiment="specter")
    (dirs["tables"] / "ns_prior_sweep.csv").write_text("\n".join(sweep_lines) + "\n", encoding="utf-8")

    _write_latex_table({"pixie": rows_pix, "specter": rows_sp})

if __name__ == "__main__":
    main()
